name: Mirro to GitLab

on:
  push:
    branches:
      - 'main' 
jobs:
  sync-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch_depth: 0
      
      - name: Mirroring Branch
        uses: codyde/branch-mirroring-action@v10
        with:
          target_repo_url: "https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.uni-oldenburg.de"
          source_branch_id: "main"
